import type { Metadata } from "next";
import { Metamorphous, Quicksand } from "next/font/google";
import "./globals.css";
import { Footer } from "./components/footer";
import { NavBar } from "./components/navBar";

const geistSans = Metamorphous({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["400"]
});

const geistMono = Quicksand({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="space"></div>
        <NavBar />
        <section className="page">
          {children}
        </section>
        <Footer />
      </body>
    </html>
  );
}
